application:
  version: 2.1.0-dev
  port: 3000

database:
  name: titanium
  host: localhost
  port: 3306

internal_resources:
  folder: resources
  path: internal

external_resources:
  folder: public
  path: content
